openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: https://byd-test-api-671247654914.us-central1.run.app
    description: Test server
paths:
  /test_image:
    get:
      summary: Ask question about an image.
      operationId: question_about_an_image
      parameters:
        - in: query
          name: image_path
          required: true
          description: Image path to load the image in Cloud Storage
          schema:
            type: string
            x-agent-input-parameter: image_path
        - in: query
          name: text
          required: true
          description: Question user is asking about the image.
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Test Endpoint Test Post
